### ISSUE TITLE
Cannot change emote codes.

### ISSUE THREAD

**Issue by Jonathan-Moore-312** [kirbyUK/pkmntcg-discord-bot#1]
I appears that I am able to change the emojis that is uses in the code directly, but when I call a command, it still uses the old emote code. Am I missing something here or is it something else?

**Comment by kirbyUK** [comment]
Have you re-run

```
make
make install
```

Since changing the emote codes?

**Comment by Jonathan-Moore-312** [comment]
No I have not . I am very new to creating and running bots, especially running on a Linux-based OS. I have done so and now it is working just fine. Thank you very much and sorry for the trouble!
